# We are using the custom profile to define our own artifacts folder
profile = "custom"
artifacts_folder = "artifacts"

[msbuild]
project = "WheelWizard.sln"
 
# We are not going to publish to nuget, scoopor brew 
[nuget]
publish = false
[scoop]
publish = false
[brew]
publish = false

[github]
user = "TeamWheelWizard"
repo = "WheelWizard"
branches = ["main"]

# Windows 
[[pack]]
rid = ["win-x64"]
kinds = ["zip"]

# Default targets for Linux/Ubuntu Debian compatible distro with debian and tar packages
[[pack]]
rid = ["linux-x64", "linux-arm", "linux-arm64"]
kinds = ["zip"]

# Default targets for macOS, only tar files for this platform
[[pack]]
rid = ["osx-x64", "osx-arm64"]
kinds = ["zip"]