//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelWizard.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WheelWizard.Resources.Languages.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the + button to add friends in Wheel Wizard.
        /// </summary>
        public static string EmptyContent_NoFriends {
            get {
                return ResourceManager.GetString("EmptyContent_NoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friends yet!.
        /// </summary>
        public static string EmptyContent_NoFriends_Title {
            get {
                return ResourceManager.GetString("EmptyContent_NoFriends_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t read the Mii data from your system. Make sure you started the game at least once.
        /// </summary>
        public static string EmptyContent_NoMiis {
            get {
                return ResourceManager.GetString("EmptyContent_NoMiis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Miis yet!.
        /// </summary>
        public static string EmptyContent_NoMiis_Title {
            get {
                return ResourceManager.GetString("EmptyContent_NoMiis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods can alter how the game works. Start importing your first mod by clicking the button below..
        /// </summary>
        public static string EmptyContent_NoMods {
            get {
                return ResourceManager.GetString("EmptyContent_NoMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mods found.
        /// </summary>
        public static string EmptyContent_NoMods_Title {
            get {
                return ResourceManager.GetString("EmptyContent_NoMods_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a mod in the list to view its details.
        /// </summary>
        public static string EmptyContent_NoModSelected {
            get {
                return ResourceManager.GetString("EmptyContent_NoModSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mod selected.
        /// </summary>
        public static string EmptyContent_NoModSelected_Title {
            get {
                return ResourceManager.GetString("EmptyContent_NoModSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to play the game at least once in order to see your profiles listed here.
        /// </summary>
        public static string EmptyContent_NoProfiles {
            get {
                return ResourceManager.GetString("EmptyContent_NoProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might not have internet connection, or no-one might be playing..
        /// </summary>
        public static string EmptyContent_NoRooms {
            get {
                return ResourceManager.GetString("EmptyContent_NoRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rooms found.
        /// </summary>
        public static string EmptyContent_NoRooms_Title {
            get {
                return ResourceManager.GetString("EmptyContent_NoRooms_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mod File.
        /// </summary>
        public static string FilePicker_SelectModFile {
            get {
                return ResourceManager.GetString("FilePicker_SelectModFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator name must be less than 11 characters long..
        /// </summary>
        public static string HelperNote_CreatorNameLess11 {
            get {
                return ResourceManager.GetString("HelperNote_CreatorNameLess11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names must be between 3 and 10 characters long..
        /// </summary>
        public static string HelperNote_NameMustBetween {
            get {
                return ResourceManager.GetString("HelperNote_NameMustBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no friends online.
        /// </summary>
        public static string Hover_FriendsOnline_0 {
            get {
                return ResourceManager.GetString("Hover_FriendsOnline_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently 1 friend online.
        /// </summary>
        public static string Hover_FriendsOnline_1 {
            get {
                return ResourceManager.GetString("Hover_FriendsOnline_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently {$1} friends online.
        /// </summary>
        public static string Hover_FriendsOnline_x {
            get {
                return ResourceManager.GetString("Hover_FriendsOnline_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friends directly here, then launch the game to sync..
        /// </summary>
        public static string Hover_FriendsPageDisclaimer {
            get {
                return ResourceManager.GetString("Hover_FriendsPageDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no players online.
        /// </summary>
        public static string Hover_PlayersOnline_0 {
            get {
                return ResourceManager.GetString("Hover_PlayersOnline_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently 1 player online.
        /// </summary>
        public static string Hover_PlayersOnline_1 {
            get {
                return ResourceManager.GetString("Hover_PlayersOnline_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently {$1} players online.
        /// </summary>
        public static string Hover_PlayersOnline_x {
            get {
                return ResourceManager.GetString("Hover_PlayersOnline_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary profile is used as reference in the wheel wizard client.
        /// </summary>
        public static string Hover_PrimaryProfile {
            get {
                return ResourceManager.GetString("Hover_PrimaryProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This only shows regions YOU have played on.
        /// </summary>
        public static string Hover_RegionUserSelection {
            get {
                return ResourceManager.GetString("Hover_RegionUserSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no active rooms.
        /// </summary>
        public static string Hover_RoomsOnline_0 {
            get {
                return ResourceManager.GetString("Hover_RoomsOnline_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently 1 room active.
        /// </summary>
        public static string Hover_RoomsOnline_1 {
            get {
                return ResourceManager.GetString("Hover_RoomsOnline_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently {$1} rooms active.
        /// </summary>
        public static string Hover_RoomsOnline_x {
            get {
                return ResourceManager.GetString("Hover_RoomsOnline_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that this page does not offer any functionality to join a room directly.
        ///To join a specific room, you&apos;ll need to either join through a friend, or hope to join it by joining the online servers..
        /// </summary>
        public static string Hover_RoomsPageDisclaimer {
            get {
                return ResourceManager.GetString("Hover_RoomsPageDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply an update. Aborting..
        /// </summary>
        public static string MessageError_AbortRR_Extra_FailedUpdateApply {
            get {
                return ResourceManager.GetString("MessageError_AbortRR_Extra_FailedUpdateApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete files for the update. Aborting..
        /// </summary>
        public static string MessageError_AbortRR_Extra_FailedUpdateDelete {
            get {
                return ResourceManager.GetString("MessageError_AbortRR_Extra_FailedUpdateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path detected. Please contact the developers.\n Server error:  {$1}.
        /// </summary>
        public static string MessageError_AbortRR_Extra_InvalidFilePath {
            get {
                return ResourceManager.GetString("MessageError_AbortRR_Extra_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting RR Update.
        /// </summary>
        public static string MessageError_AbortRR_Title {
            get {
                return ResourceManager.GetString("MessageError_AbortRR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move data.
        /// </summary>
        public static string MessageError_DataFolderMove_Title {
            get {
                return ResourceManager.GetString("MessageError_DataFolderMove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Change Mii.
        /// </summary>
        public static string MessageError_FailedChangeMii_Title {
            get {
                return ResourceManager.GetString("MessageError_FailedChangeMii_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change name.
        /// </summary>
        public static string MessageError_FailedChangeName_Title {
            get {
                return ResourceManager.GetString("MessageError_FailedChangeName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Mii database.
        /// </summary>
        public static string MessageError_FailedCreateMiiDb_Title {
            get {
                return ResourceManager.GetString("MessageError_FailedCreateMiiDb_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of Dolphin Emulator failed. Please try manually installing Flatpak Dolphin..
        /// </summary>
        public static string MessageError_FailedInstallDolphin_Extra {
            get {
                return ResourceManager.GetString("MessageError_FailedInstallDolphin_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install Dolphin.
        /// </summary>
        public static string MessageError_FailedInstallDolphin_Title {
            get {
                return ResourceManager.GetString("MessageError_FailedInstallDolphin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve mod info.
        /// </summary>
        public static string MessageError_FailedRetrieveMod_Title {
            get {
                return ResourceManager.GetString("MessageError_FailedRetrieveMod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        public static string MessageError_GenericError_Title {
            get {
                return ResourceManager.GetString("MessageError_GenericError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during download: {$1}.
        /// </summary>
        public static string MessageError_ModDownloadFail_Extra {
            get {
                return ResourceManager.GetString("MessageError_ModDownloadFail_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod download failed..
        /// </summary>
        public static string MessageError_ModDownloadFail_Title {
            get {
                return ResourceManager.GetString("MessageError_ModDownloadFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod folder does not exist.
        /// </summary>
        public static string MessageError_NoModFolder_Extra {
            get {
                return ResourceManager.GetString("MessageError_NoModFolder_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart with administrator rights..
        /// </summary>
        public static string MessageError_RestartAdminFail_Extra {
            get {
                return ResourceManager.GetString("MessageError_RestartAdminFail_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel Wizard data is now stored in:\n{$1}.
        /// </summary>
        public static string MessageSuccess_DataFolderMoved_Extra {
            get {
                return ResourceManager.GetString("MessageSuccess_DataFolderMoved_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data folder updated.
        /// </summary>
        public static string MessageSuccess_DataFolderMoved_Title {
            get {
                return ResourceManager.GetString("MessageSuccess_DataFolderMoved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mii changed successfully.
        /// </summary>
        public static string MessageSuccess_MiiChanged {
            get {
                return ResourceManager.GetString("MessageSuccess_MiiChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted to patches.
        /// </summary>
        public static string MessageSuccess_ModConvertedToPatches_Title {
            get {
                return ResourceManager.GetString("MessageSuccess_ModConvertedToPatches_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod &apos;{$1}&apos; installed successfully..
        /// </summary>
        public static string MessageSuccess_ModInstalled_Extra {
            get {
                return ResourceManager.GetString("MessageSuccess_ModInstalled_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed mod!.
        /// </summary>
        public static string MessageSuccess_ModInstalled_Title {
            get {
                return ResourceManager.GetString("MessageSuccess_ModInstalled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted {$1} file(s) into {$2} patch file(s)..
        /// </summary>
        public static string MessageSuccess_PatchConversionResult {
            get {
                return ResourceManager.GetString("MessageSuccess_PatchConversionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left {$1} file(s) unchanged because they could not be converted..
        /// </summary>
        public static string MessageSuccess_PatchConversionSkipped {
            get {
                return ResourceManager.GetString("MessageSuccess_PatchConversionSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retro Rewind is up to date..
        /// </summary>
        public static string MessageSuccess_RRUpToDate_Title {
            get {
                return ResourceManager.GetString("MessageSuccess_RRUpToDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully!.
        /// </summary>
        public static string MessageSuccess_SettingsSaved_Title {
            get {
                return ResourceManager.GetString("MessageSuccess_SettingsSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the selected Mii(s) is a favorite. Miis can only be deleted if they are not favorites to prevent accidental deletions..
        /// </summary>
        public static string MessageWarning_CannotDeleteFavMii_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_CannotDeleteFavMii_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete favorite Mii(s).
        /// </summary>
        public static string MessageWarning_CannotDeleteFavMii_Title {
            get {
                return ResourceManager.GetString("MessageWarning_CannotDeleteFavMii_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot view mod that was not installed through the mod browser..
        /// </summary>
        public static string MessageWarning_CantViewMod_Extra_NotFromBrowser {
            get {
                return ResourceManager.GetString("MessageWarning_CantViewMod_Extra_NotFromBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when trying to open the selected mod..
        /// </summary>
        public static string MessageWarning_CantViewMod_Extra_SomethingElse {
            get {
                return ResourceManager.GetString("MessageWarning_CantViewMod_Extra_SomethingElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot view this mod..
        /// </summary>
        public static string MessageWarning_CantViewMod_Title {
            get {
                return ResourceManager.GetString("MessageWarning_CantViewMod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert mod.
        /// </summary>
        public static string MessageWarning_CouldNotConvertMod_Title {
            get {
                return ResourceManager.GetString("MessageWarning_CouldNotConvertMod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin Emulator folder not automatically found. Please try and find the folder manually, click &apos;help&apos; for more information..
        /// </summary>
        public static string MessageWarning_DolphinNotFound_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_DolphinNotFound_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin Emulator Folder Not Found.
        /// </summary>
        public static string MessageWarning_DolphinNotFound_Title {
            get {
                return ResourceManager.GetString("MessageWarning_DolphinNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected DolphinTool.exe. Please choose Dolphin.exe (the Dolphin emulator executable) instead..
        /// </summary>
        public static string MessageWarning_DolphinToolSelected_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_DolphinToolSelected_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Dolphin executable selected.
        /// </summary>
        public static string MessageWarning_DolphinToolSelected_Title {
            get {
                return ResourceManager.GetString("MessageWarning_DolphinToolSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t check for updates right now. You might not be connected to the internet or the server might be down..
        /// </summary>
        public static string MessageWarning_FailCheckUpdates_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_FailCheckUpdates_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates.
        /// </summary>
        public static string MessageWarning_FailCheckUpdates_Title {
            get {
                return ResourceManager.GetString("MessageWarning_FailCheckUpdates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mod with the name &apos;{$1}&apos; already exists..
        /// </summary>
        public static string MessageWarning_InvalidName_Extra_ModNameExists {
            get {
                return ResourceManager.GetString("MessageWarning_InvalidName_Extra_ModNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not possible..
        /// </summary>
        public static string MessageWarning_InvalidName_Title {
            get {
                return ResourceManager.GetString("MessageWarning_InvalidName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure all paths are correct and try again..
        /// </summary>
        public static string MessageWarning_InvalidPaths_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_InvalidPaths_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Paths..
        /// </summary>
        public static string MessageWarning_InvalidPaths_Title {
            get {
                return ResourceManager.GetString("MessageWarning_InvalidPaths_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a mod name..
        /// </summary>
        public static string MessageWarning_ModNameEmpty_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_ModNameEmpty_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod name can&apos;t be empty..
        /// </summary>
        public static string MessageWarning_ModNameEmpty_Title {
            get {
                return ResourceManager.GetString("MessageWarning_ModNameEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod name contains invalid characters..
        /// </summary>
        public static string MessageWarning_ModNameInvalid_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_ModNameInvalid_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod name Invalid..
        /// </summary>
        public static string MessageWarning_ModNameInvalid_Title {
            get {
                return ResourceManager.GetString("MessageWarning_ModNameInvalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Files Selected.
        /// </summary>
        public static string MessageWarning_MultipleFilesSelected_Title {
            get {
                return ResourceManager.GetString("MessageWarning_MultipleFilesSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server. Please try again later..
        /// </summary>
        public static string MessageWarning_NoConnectServer_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_NoConnectServer_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server.
        /// </summary>
        public static string MessageWarning_NoConnectServer_Title {
            get {
                return ResourceManager.GetString("MessageWarning_NoConnectServer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Dolphin Emulator, please set the path in settings.
        /// </summary>
        public static string MessageWarning_NotFindDolphin_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_NotFindDolphin_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the game, please set the path in settings.
        /// </summary>
        public static string MessageWarning_NotFindGame_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_NotFindGame_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files could not be found..
        /// </summary>
        public static string MessageWarning_UnableDownloadMod_Extra {
            get {
                return ResourceManager.GetString("MessageWarning_UnableDownloadMod_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download the mod.
        /// </summary>
        public static string MessageWarning_UnableDownloadMod_Title {
            get {
                return ResourceManager.GetString("MessageWarning_UnableDownloadMod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Wheel Wizard. Please ensure the application is located in a folder that can be written to.\n Could not find current folder..
        /// </summary>
        public static string MessageWarning_UnableUpdateWhWz_Extra_ReasonLocation {
            get {
                return ResourceManager.GetString("MessageWarning_UnableUpdateWhWz_Extra_ReasonLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check if Wheel Wizard is up to date. \nYou might be experiencing network issues..
        /// </summary>
        public static string MessageWarning_UnableUpdateWhWz_Extra_ReasonNetwork {
            get {
                return ResourceManager.GetString("MessageWarning_UnableUpdateWhWz_Extra_ReasonNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Wheel Wizard..
        /// </summary>
        public static string MessageWarning_UnableUpdateWhWz_Title {
            get {
                return ResourceManager.GetString("MessageWarning_UnableUpdateWhWz_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mod is incompatible with other mods. Launching with this mod enabled may cause incorrect behavior or crashes. Consider converting it to patches by right-clicking the mod..
        /// </summary>
        public static string Patch_IncompatibleMod_Message {
            get {
                return ResourceManager.GetString("Patch_IncompatibleMod_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCOMPATIBLE MOD.
        /// </summary>
        public static string Patch_IncompatibleMod_Title {
            get {
                return ResourceManager.GetString("Patch_IncompatibleMod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mii name....
        /// </summary>
        public static string Placeholder_EnterMiiName {
            get {
                return ResourceManager.GetString("Placeholder_EnterMiiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter mod name....
        /// </summary>
        public static string Placeholder_EnterModName {
            get {
                return ResourceManager.GetString("Placeholder_EnterModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter desired path here....
        /// </summary>
        public static string Placeholder_EnterPath {
            get {
                return ResourceManager.GetString("Placeholder_EnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text here....
        /// </summary>
        public static string Placeholder_EnterTextHere {
            get {
                return ResourceManager.GetString("Placeholder_EnterTextHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For Players....
        /// </summary>
        public static string Placeholder_SearchForPlayers {
            get {
                return ResourceManager.GetString("Placeholder_SearchForPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for mods....
        /// </summary>
        public static string Placeholder_SearchMod {
            get {
                return ResourceManager.GetString("Placeholder_SearchMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying converted mod.
        /// </summary>
        public static string Progress_ApplyingConvertedMod {
            get {
                return ResourceManager.GetString("Progress_ApplyingConvertedMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining files.
        /// </summary>
        public static string Progress_CombiningFiles {
            get {
                return ResourceManager.GetString("Progress_CombiningFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting {$1}.
        /// </summary>
        public static string Progress_ConvertingFile {
            get {
                return ResourceManager.GetString("Progress_ConvertingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting {$1} file(s).
        /// </summary>
        public static string Progress_ConvertingFilesCount {
            get {
                return ResourceManager.GetString("Progress_ConvertingFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting mod to patches.
        /// </summary>
        public static string Progress_ConvertingModToPatches {
            get {
                return ResourceManager.GetString("Progress_ConvertingModToPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading {$1} MB.
        /// </summary>
        public static string Progress_DownloadingMb {
            get {
                return ResourceManager.GetString("Progress_DownloadingMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {$1}.
        /// </summary>
        public static string Progress_DownloadingMod {
            get {
                return ResourceManager.GetString("Progress_DownloadingMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time remaining:.
        /// </summary>
        public static string Progress_EstimatedTimeRemaining {
            get {
                return ResourceManager.GetString("Progress_EstimatedTimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Dolphin Emulator.
        /// </summary>
        public static string Progress_InstallingDolphin {
            get {
                return ResourceManager.GetString("Progress_InstallingDolphin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Mod.
        /// </summary>
        public static string Progress_InstallingMod {
            get {
                return ResourceManager.GetString("Progress_InstallingMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing mods.
        /// </summary>
        public static string Progress_InstallingMods {
            get {
                return ResourceManager.GetString("Progress_InstallingMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {$1} mods.
        /// </summary>
        public static string Progress_InstallingModsCount {
            get {
                return ResourceManager.GetString("Progress_InstallingModsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Retro Rewind.
        /// </summary>
        public static string Progress_InstallingRR {
            get {
                return ResourceManager.GetString("Progress_InstallingRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Retro Rewind for the first time.
        /// </summary>
        public static string Progress_InstallingRRFirstTime {
            get {
                return ResourceManager.GetString("Progress_InstallingRRFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the latest Wheel Wizard from github releases.
        /// </summary>
        public static string Progress_LatestWhWzGithub {
            get {
                return ResourceManager.GetString("Progress_LatestWhWzGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing {$1} file(s).
        /// </summary>
        public static string Progress_PreparingFilesCount {
            get {
                return ResourceManager.GetString("Progress_PreparingFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {$1} of {$2} files....
        /// </summary>
        public static string Progress_ProcessingXofY {
            get {
                return ResourceManager.GetString("Progress_ProcessingXofY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take a while depending on your internet connection..
        /// </summary>
        public static string Progress_ThisMayTakeAWhile {
            get {
                return ResourceManager.GetString("Progress_ThisMayTakeAWhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Retro Rewind.
        /// </summary>
        public static string Progress_UpdateRR {
            get {
                return ResourceManager.GetString("Progress_UpdateRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Wheel Wizard.
        /// </summary>
        public static string Progress_UpdateWhWz {
            get {
                return ResourceManager.GetString("Progress_UpdateWhWz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will revert in {$1} unless you decide to keep the change..
        /// </summary>
        public static string Question_ApplyScale_Extra {
            get {
                return ResourceManager.GetString("Question_ApplyScale_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to apply the new scale?.
        /// </summary>
        public static string Question_ApplyScale_Title {
            get {
                return ResourceManager.GetString("Question_ApplyScale_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Flatpak version of Dolphin Emulator does not appear to be installed. Would you like us to install it (system-wide)?.
        /// </summary>
        public static string Question_DolphinFlatpack_Extra {
            get {
                return ResourceManager.GetString("Question_DolphinFlatpack_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin Flatpak Installation.
        /// </summary>
        public static string Question_DolphinFlatpack_Title {
            get {
                return ResourceManager.GetString("Question_DolphinFlatpack_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you dont know what all of this means, just click yes :) \nDolphin Emulator folder found. Would you like to use this folder?.
        /// </summary>
        public static string Question_DolphinFound_Extra {
            get {
                return ResourceManager.GetString("Question_DolphinFound_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin Emulator Folder Found.
        /// </summary>
        public static string Question_DolphinFound_Title {
            get {
                return ResourceManager.GetString("Question_DolphinFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod name:.
        /// </summary>
        public static string Question_EnterModName_Title {
            get {
                return ResourceManager.GetString("Question_EnterModName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing name from: {$1}.
        /// </summary>
        public static string Question_EnterNewName_Extra {
            get {
                return ResourceManager.GetString("Question_EnterNewName_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new name.
        /// </summary>
        public static string Question_EnterNewName_Title {
            get {
                return ResourceManager.GetString("Question_EnterNewName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download and install the mod: {$1}?.
        /// </summary>
        public static string Question_InstallMod_Title {
            get {
                return ResourceManager.GetString("Question_InstallMod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to launch the game without any mods. Do you want to clear your my-stuff folder?.
        /// </summary>
        public static string Question_LaunchClearModsFound_Extra {
            get {
                return ResourceManager.GetString("Question_LaunchClearModsFound_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods found.
        /// </summary>
        public static string Question_LaunchClearModsFound_Title {
            get {
                return ResourceManager.GetString("Question_LaunchClearModsFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to launch the game without mods. Do you want to clear your Patches folder? Launching your game anyways will launch it with the current patches folder still active!.
        /// </summary>
        public static string Question_LaunchClearPatchesFound_Extra {
            get {
                return ResourceManager.GetString("Question_LaunchClearPatchesFound_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel Wizard will move its files to:\n{$1}\nThis may take a while depending on the amount of data..
        /// </summary>
        public static string Question_MoveData_Extra {
            get {
                return ResourceManager.GetString("Question_MoveData_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Wheel Wizard data?.
        /// </summary>
        public static string Question_MoveData_Title {
            get {
                return ResourceManager.GetString("Question_MoveData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {$1} of Wheel Wizard is available (currently on {$2}). Do you want to update now?.
        /// </summary>
        public static string Question_NewVersionWhWz_Extra {
            get {
                return ResourceManager.GetString("Question_NewVersionWhWz_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel Wizard Update Available.
        /// </summary>
        public static string Question_NewVersionWhWz_Title {
            get {
                return ResourceManager.GetString("Question_NewVersionWhWz_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old save data was found. Would you like to use it? (recommended).
        /// </summary>
        public static string Question_OldRksysFound_Extra {
            get {
                return ResourceManager.GetString("Question_OldRksysFound_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old rksys.dat found.
        /// </summary>
        public static string Question_OldRksysFound_Title {
            get {
                return ResourceManager.GetString("Question_OldRksysFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reinstall Retro Rewind?.
        /// </summary>
        public static string Question_ReinstallRR_Extra {
            get {
                return ResourceManager.GetString("Question_ReinstallRR_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall Retro Rewind.
        /// </summary>
        public static string Question_ReinstallRR_Title {
            get {
                return ResourceManager.GetString("Question_ReinstallRR_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of Retro Rewind could not be determined. Would you like to download Retro Rewind?.
        /// </summary>
        public static string Question_RRNotDeterment_Extra {
            get {
                return ResourceManager.GetString("Question_RRNotDeterment_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Retro Rewind.
        /// </summary>
        public static string Question_RRNotDeterment_Title {
            get {
                return ResourceManager.GetString("Question_RRNotDeterment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of Retro Rewind is too old to update. Would you like to reinstall Retro Rewind?.
        /// </summary>
        public static string Question_RRToOld_Extra {
            get {
                return ResourceManager.GetString("Question_RRToOld_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Retro Rewind version is too old..
        /// </summary>
        public static string Question_RRToOld_Title {
            get {
                return ResourceManager.GetString("Question_RRToOld_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for mods....
        /// </summary>
        public static string Question_SearchMod {
            get {
                return ResourceManager.GetString("Question_SearchMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting is permanent and cannot be undone..
        /// </summary>
        public static string Question_SureDelete_Extra {
            get {
                return ResourceManager.GetString("Question_SureDelete_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {$1}?.
        /// </summary>
        public static string Question_SureDelete_Title {
            get {
                return ResourceManager.GetString("Question_SureDelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {$1} Miis?.
        /// </summary>
        public static string Question_SureDelete_Title_Miis {
            get {
                return ResourceManager.GetString("Question_SureDelete_Title_Miis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes an update requires admin rights, do you want to active them for this update?.
        /// </summary>
        public static string Question_UpdateAdmin_Extra {
            get {
                return ResourceManager.GetString("Question_UpdateAdmin_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update using admin.
        /// </summary>
        public static string Question_UpdateAdmin_Title {
            get {
                return ResourceManager.GetString("Question_UpdateAdmin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Mii &apos;{$1}&apos;.
        /// </summary>
        public static string SnackbarError_MiiFailureCreate {
            get {
                return ResourceManager.GetString("SnackbarError_MiiFailureCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize Mii &apos;{$1}&apos;.
        /// </summary>
        public static string SnackbarError_MiiFailureDeserialize {
            get {
                return ResourceManager.GetString("SnackbarError_MiiFailureDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to duplicate Mii(s) &apos;{$1}&apos;.
        /// </summary>
        public static string SnackbarError_MiiFailureDuplicate {
            get {
                return ResourceManager.GetString("SnackbarError_MiiFailureDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get Mii &apos;{$1}&apos;.
        /// </summary>
        public static string SnackbarError_MiiFailureGet {
            get {
                return ResourceManager.GetString("SnackbarError_MiiFailureGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save Mii &apos;{$1}&apos;.
        /// </summary>
        public static string SnackbarError_MiiFailureSave {
            get {
                return ResourceManager.GetString("SnackbarError_MiiFailureSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to serialize Mii &apos;{$1}&apos;.
        /// </summary>
        public static string SnackbarError_MiiFailureSerialize {
            get {
                return ResourceManager.GetString("SnackbarError_MiiFailureSerialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Mii &apos;{$1}&apos;.
        /// </summary>
        public static string SnackbarError_MiiFailureUpdate {
            get {
                return ResourceManager.GetString("SnackbarError_MiiFailureUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied friend code to clipboard.
        /// </summary>
        public static string SnackbarSuccess_CopiedFC {
            get {
                return ResourceManager.GetString("SnackbarSuccess_CopiedFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created duplicate of &apos;{$1}&apos;.
        /// </summary>
        public static string SnackbarSuccess_CreatedDuplicate {
            get {
                return ResourceManager.GetString("SnackbarSuccess_CreatedDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {$1} duplicate Miis.
        /// </summary>
        public static string SnackbarSuccess_CreatedDuplicatesMiis {
            get {
                return ResourceManager.GetString("SnackbarSuccess_CreatedDuplicatesMiis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted &apos;{$1}&apos;.
        /// </summary>
        public static string SnackbarSuccess_Deleted {
            get {
                return ResourceManager.GetString("SnackbarSuccess_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {$1} Miis.
        /// </summary>
        public static string SnackbarSuccess_Deleted_Miis {
            get {
                return ResourceManager.GetString("SnackbarSuccess_Deleted_Miis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mii has been added to your Miis.
        /// </summary>
        public static string SnackbarSuccess_MiiAdded {
            get {
                return ResourceManager.GetString("SnackbarSuccess_MiiAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed name to &apos;{$1}&apos;.
        /// </summary>
        public static string SnackbarSuccess_NameChange {
            get {
                return ResourceManager.GetString("SnackbarSuccess_NameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set profile as primary.
        /// </summary>
        public static string SnackbarSuccess_ProfileSetPrimary {
            get {
                return ResourceManager.GetString("SnackbarSuccess_ProfileSetPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Mii &apos;{$1}&apos; to file &apos;{$2}&apos;.
        /// </summary>
        public static string SnackbarSuccess_SavedMii {
            get {
                return ResourceManager.GetString("SnackbarSuccess_SavedMii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Save Mii.
        /// </summary>
        public static string SnackbarWarning_CantSaveMii {
            get {
                return ResourceManager.GetString("SnackbarWarning_CantSaveMii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems there where no Miis to delete.
        /// </summary>
        public static string SnackbarWarning_NoMiiDelete {
            get {
                return ResourceManager.GetString("SnackbarWarning_NoMiiDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems there where no Miis to export.
        /// </summary>
        public static string SnackbarWarning_NoMiiExport {
            get {
                return ResourceManager.GetString("SnackbarWarning_NoMiiExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1} entry {$2}.
        /// </summary>
        public static string Text_BrsarEntry {
            get {
                return ResourceManager.GetString("Text_BrsarEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1} entry {$2} + RWAR.
        /// </summary>
        public static string Text_BrsarEntryWithRwar {
            get {
                return ResourceManager.GetString("Text_BrsarEntryWithRwar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External reference.
        /// </summary>
        public static string Text_ExternalReference {
            get {
                return ResourceManager.GetString("Text_ExternalReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External reference: {$1}.
        /// </summary>
        public static string Text_ExternalReferenceWithPath {
            get {
                return ResourceManager.GetString("Text_ExternalReferenceWithPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This language is translated by: {$1}.
        /// </summary>
        public static string Text_LanguageTranslatedBy {
            get {
                return ResourceManager.GetString("Text_LanguageTranslatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by: {$1} \n And {$2}.
        /// </summary>
        public static string Text_MadeByString {
            get {
                return ResourceManager.GetString("Text_MadeByString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified archive member.
        /// </summary>
        public static string Text_ModifiedArchiveMember {
            get {
                return ResourceManager.GetString("Text_ModifiedArchiveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New archive member.
        /// </summary>
        public static string Text_NewArchiveMember {
            get {
                return ResourceManager.GetString("Text_NewArchiveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By GameBanana.
        /// </summary>
        public static string Text_PoweredGamebanana {
            get {
                return ResourceManager.GetString("Text_PoweredGamebanana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks a lot to all the translators:.
        /// </summary>
        public static string Text_ThanksTranslators {
            get {
                return ResourceManager.GetString("Text_ThanksTranslators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole-file override.
        /// </summary>
        public static string Text_WholeFileOverride {
            get {
                return ResourceManager.GetString("Text_WholeFileOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations for this language are {$1}% complete.
        /// </summary>
        public static string Text_WhWzTranslationPercentage {
            get {
                return ResourceManager.GetString("Text_WhWzTranslationPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string Time_Days_1 {
            get {
                return ResourceManager.GetString("Time_Days_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1} days.
        /// </summary>
        public static string Time_Days_x {
            get {
                return ResourceManager.GetString("Time_Days_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string Time_Hours_1 {
            get {
                return ResourceManager.GetString("Time_Hours_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1}  hours.
        /// </summary>
        public static string Time_Hours_x {
            get {
                return ResourceManager.GetString("Time_Hours_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        public static string Time_Minutes_1 {
            get {
                return ResourceManager.GetString("Time_Minutes_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1} minutes.
        /// </summary>
        public static string Time_Minutes_x {
            get {
                return ResourceManager.GetString("Time_Minutes_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 second.
        /// </summary>
        public static string Time_Seconds_1 {
            get {
                return ResourceManager.GetString("Time_Seconds_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1} seconds.
        /// </summary>
        public static string Time_Seconds_x {
            get {
                return ResourceManager.GetString("Time_Seconds_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1} BRSAR file entries are external references and cannot be exported..
        /// </summary>
        public static string Warning_BrsarExternalCount {
            get {
                return ResourceManager.GetString("Warning_BrsarExternalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRSAR fileId {$1} is an external file reference and cannot be exported..
        /// </summary>
        public static string Warning_BrsarFileIdExternal {
            get {
                return ResourceManager.GetString("Warning_BrsarFileIdExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRSAR fileId {$1} could not be resolved to a supported embedded sound file..
        /// </summary>
        public static string Warning_BrsarFileIdUnresolved {
            get {
                return ResourceManager.GetString("Warning_BrsarFileIdUnresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRSAR fileId {$1} changed, but it resolves to {$2} and Pulsar only supports RBNK/RSEQ/RWSD loose overrides..
        /// </summary>
        public static string Warning_BrsarFileIdUnsupportedMagic {
            get {
                return ResourceManager.GetString("Warning_BrsarFileIdUnsupportedMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported RBNK/RSEQ/RWSD differences were found against the built-in game baseline..
        /// </summary>
        public static string Warning_BrsarNoSupportedDifferences {
            get {
                return ResourceManager.GetString("Warning_BrsarNoSupportedDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1} embedded BRSAR file entries could not be resolved confidently..
        /// </summary>
        public static string Warning_BrsarUnresolvedCount {
            get {
                return ResourceManager.GetString("Warning_BrsarUnresolvedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only RBNK/RSEQ/RWSD entries can be exported. The scanned archive also contains {$1}..
        /// </summary>
        public static string Warning_BrsarUnsupportedSummary {
            get {
                return ResourceManager.GetString("Warning_BrsarUnsupportedSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1} exists only in the original archive. File deletions are not exportable as loose patches..
        /// </summary>
        public static string Warning_FileDeletionNotExportable {
            get {
                return ResourceManager.GetString("Warning_FileDeletionNotExportable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file name differs from the original archive tag &quot;{$1}.szs&quot;..
        /// </summary>
        public static string Warning_FileNameDiffersFromArchiveTag {
            get {
                return ResourceManager.GetString("Warning_FileNameDiffersFromArchiveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1} is not present in the built-in game baseline..
        /// </summary>
        public static string Warning_FileNotInBuiltInBaseline {
            get {
                return ResourceManager.GetString("Warning_FileNotInBuiltInBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SZS differences were found against the built-in game baseline..
        /// </summary>
        public static string Warning_NoSzsDifferences {
            get {
                return ResourceManager.GetString("Warning_NoSzsDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected SZS matches the built-in game baseline exactly..
        /// </summary>
        public static string Warning_SzsMatchesBaseline {
            get {
                return ResourceManager.GetString("Warning_SzsMatchesBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$1} uses an unsupported loose override extension (.kcl, .kmp, .slt)..
        /// </summary>
        public static string Warning_UnsupportedLooseOverrideExtension {
            get {
                return ResourceManager.GetString("Warning_UnsupportedLooseOverrideExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SZS is stored as a whole-file baseline. Exporting a whole-file override..
        /// </summary>
        public static string Warning_WholeFileBaseline {
            get {
                return ResourceManager.GetString("Warning_WholeFileBaseline", resourceCulture);
            }
        }
    }
}
