name: CI/CD
permissions: write-all
on:
  push:
    branches: [ "main", "dev" ]
    tags:
      - *
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Build, Tests, Cover, Pack and Publish (on push tag)
        shell: bash
        run: |
          dotnet tool install --global dotnet-releaser
          dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml
